@host = localhost:4004

###
# GET Metadata
GET http://{{host}}/odata/v4/git-hub/$metadata HTTP/1.1
Accept: application/json

###
# GET Issues
GET http://{{host}}/odata/v4/git-hub/Issue?$count=true&$top=10 HTTP/1.1
Accept: application/json

###
# GET Issues Count
GET http://{{host}}/odata/v4/git-hub/Issue/$count HTTP/1.1
Accept: application/json

###
# GET Issues with filter
GET http://{{host}}/odata/v4/git-hub/Issue?$count=true&$filter=state%20eq%20'open'%20and%20label%20eq%20'Test'%20and%20'assignee'%20eq%20'x-sebvogel'

###
# GET Issue 324
GET http://{{host}}/odata/v4/git-hub/Issue/324 HTTP/1.1
Accept: application/json

###
# POST new Issue
POST http://{{host}}/odata/v4/git-hub/createIssue HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "title": "Test Issue from REST Client",
  "body": "This issue was created using the VSCode REST Client."
}
